# Default values for my-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: my-hello-app
  # For local images built with `eval $(minikube docker-env)`,
  # IfNotPresent ensures K8s uses the local image instead of trying to pull from Docker Hub.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: NodePort
  port: 80

ingress:
  enabled: false
