apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-app-deployment-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-app-secret
  template:
    metadata:
      labels:
        app: config-app-secret
    spec:
      containers:
      - name: config-app
        image: config-app:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: config-app-secret
