apiVersion: v1
kind: Service
metadata:
  name: stateful-app-headless
spec:
  clusterIP: None # This makes the service "headless"
  selector:
    app: stateful-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
