apiVersion: batch/v1
kind: CronJob
metadata:
  name: repeating-hello
spec:
  # Run every minute
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command:
            - /bin/sh
            - -c
            - date; echo "Hello from the CronJob!"
          restartPolicy: OnFailure
