apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: monitoring-app
        image: monitoring-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-app-service
spec:
  selector:
    app: monitoring-app
  ports:
    - protocol: TCP
      port: 3000 # Expose on port 3000
      targetPort: 3000
