apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probes-app
  template:
    metadata:
      labels:
        app: probes-app
    spec:
      containers:
      - name: probes-app
        image: probes-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: probes-app-service
spec:
  selector:
    app: probes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
